# Generated by Django 3.2.9 on 2022-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='logo/'),
        ),
    ]
